### ISSUE TITLE
Unexpected error - strings not equal

### ISSUE THREAD

**Issue by jazanne** [steinfletcher/apitest-jsonpath#49]
Here is my assertion:

```go
jsonpath.Equal(`$.items[?(@._links.parent.href == "PATH")].name`), "active"),
```

And the error I'm getting

```
Received unexpected error:
"[active]" not equal to "active"
```

So i changed to This
```go
jsonpath.Equal(`$.items[?(@._links.parent.href == "PATH")].name`), "[active]"),
```

and now the error is...
```
Received unexpected error:
"[active]" not equal to "[active]"
```

**Comment by steinfletcher** [comment]
Hey @jazanne. I think in the first case you get back an array, so the comparison fails, since it's comparing an array with a string, rather than the literal "[active]"
