### ISSUE TITLE
Array equality question

### ISSUE THREAD

**Issue by TrueWill** [steinfletcher/apitest-jsonpath#51]
Probably more of a question than an issue, but possibly the documentation could reflect this.

Given JSON like

```json
[
  {
    "id": 1,
    "created_at": "2023-04-21"
  },
  {
    "id": 2,
    "created_at": "2023-04-22"
  },
  {
    "id": 3,
    "created_at": "2023-04-23"
  },
  {
    "id": 4,
    "created_at": "2023-04-24"
  }
]
```

Then asserting

```go
Assert(jsonpath.Equal(`$[*].id`, [4]float64{1, 2, 3, 4}))
```

Results in

`"[%!s(float64=1) %!s(float64=2) %!s(float64=3) %!s(float64=4)]" not equal to "[%!s(float64=1) %!s(float64=2) %!s(float64=3) %!s(float64=4)]"`

Those look identical.

What's the correct way to assert on all of the IDs at once?

**Comment by oslivan** [comment]
@TrueWill The problem as below:
```go
Expected value: []float64{1, 2, 3, 4}
Actual value: []interface{}{1, 2, 3, 4}
```
When use `reflect.DeepEqual` to compare, it shouldn't be identical, so you can change expected value as `[]interface{}{1.0, 2.0, 3.0, 4.0}`. The case will be pass.
